--TODO: one can use `TSQuery:disable_capture` to disable all the captures, except for @string and @comment, and the use that as the query (does it also effect the global query?) instead of having a list (or just make it an option as always)

return {
    nodes={
        string={
            'string',
            'multiline_string',
            'char',
            'character',
            --bash/sh
            'raw_string',
            --c/cpp
            'char_literal',
            'string_literal',
            --css
            'string_value',
            --clojure/commonlisp
            'str_lit',
            'char_lit',
            --go
            'interpreted_string_literal',
            'raw_string_literal',
            'rune_literal',
            --html
            'quoted_attribute_value',
            --javascript
            'template_string',
            --d #62
            'string_literals',
            --cs
            'interpolated_string_expression',
            'verbatim_string_literal',
            'character_literal',
            --perl
            'interpolated_string_literal',
        },comment={
            'comment',
            'multiline_comment',
            --d #62
            'line_comment',
            'block_comment',
            'nesting_block_comment',
            --nim
            'documentation_comment',
            'block_documentation_comment',
        }},
    inclusive_pattern={
        -- https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(syntax)#Comments
        -- https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(strings)#String_literals
        comment={
            ';',
            '//',
            '#',
            '--',
            '%',
            vim='"',
            fortran='!',
            slim='/',
            xdefaults='!',
            forth='\\',
            rst='..',
        },
        string={
            fend=':',
            '?',
        }
    },exclusive_pattern={
        string={
            {'"','"'},
            {"'","'"},
            lua={'%[(=*)%[','%](=*)%]',patt=true},
            cs={{'$"','"'},{'@"','"'},multi=true},
            perl={'qq?%s*(.)','(.)',patt=true},
            ruby={{'%%Q(.)','(.)',patt=true},{'%%(.)','(.)',patt=true},multi=true},
            {'`','`'},
            python={'[frub][frub]?([\'"])','([\'"])',patt=true},
            d={'q"(.)','(.)"',patt=true},
            {'r"','"'},
            cpp={'R"(',')"'},
            rust={'r#"','"#'},
            {"L'","'"},
            {'L"','"'},{'u8"','"'},{'u"','"'},{'U"','"'},
        },
        comment={
            {'/*','*/'},
            ruby={'=begin','=end'},
            {'<!--','-->'},
            julia={'#=','=#'},
            {'#|','|#'},
            powershell={{'<#','#>'},{'@"','"@'},multi=true},
            {'(*','*)'},
            lua={'%-%-%[(=*)%[','%](=*)%]',patt=true},
            matlab={'%{','%}'},
            {'{','}'},
            eruby={'<%#','%>'},
            nim={'#[',']#'},
            d={'/+','+/'},
            heex={'<%!--','--%>'},
            forth={'(',')'}
        },
    },
}
